---

version: "3"

services:
  http:
    image: service_test
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql://tester:testing@postgres/library
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: library